### ISSUE TITLE
Manage not working !

### ISSUE THREAD

**Issue by kamrulHasan12** [KeyAuth/KeyAuth-Source-Code#29]
Hello there, Keyauth's Roles arent working fine. When I try to make a reseller panel, my role auto get back to developer/seller to tester somehow!

**Comment by Aspect0002** [comment]
hey, this is because it sets the sub to 1970

**Comment by wnelson03** [comment]
This is probably because you just changed the role column and didn't change the expiry column. If you do this, yes it will set it back.

The easiest way to do it is to go to the database, and change the `admin` column for your account to `1` then after that, you should go to https://example.com/admin/ and search by username to find your account. then click edit and set your account to the desired role. After doing it like this, you shouldn't have any issues.
