### ISSUE TITLE
Forgot page missing in source code

### ISSUE THREAD

**Issue by mdp18** [KeyAuth/KeyAuth-Source-Code#32]
removed as owner doesnt want it out in the public.

**Comment by wnelson03** [comment]
Yeah, also I wouldn't recommend using that old forgot source code because a bad actor could easily mess with a user and change their password if they knew their email. They couldn't get into the account, but it would still interfere with the user who wants to log into their account. Now, I send a password reset link so only people with access to the email inbox can change the password. I'm also using Mailjet, an email API, since the last two service providers I've used (OVH & Kamatera) are listed in email spam blocks. So, if I were not using an email API, outlook email addresses for example would not recieve the email.
