### ISSUE TITLE
License Level for File Downloads

### ISSUE THREAD

**Issue by ghost** [KeyAuth/KeyAuth-Source-Code#52]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
Since you can make different subscriptions (with different license levels) it would be cool to add a required license level in order to download files. There is already the checkbox "Authenticated" but it would be nice to have a required license level for downloading a file so the requested file to download matches the subscription.

**Screenshots**
I made a poc with paint how it could look like: [https://cdn.discordapp.com/attachments/907400214367838228/967389954462322728/unknown.png](url)

**Comment by wnelson03** [comment]
I would probably do subscription name rather than the license level. It would take less queries and be more simple.

You only want the file to be locked to just one subscription? That would be real simple, I was expecting people were going to want to lock files to more than one subscription. Though if it were just one subscription, that'd be easier.

**Comment by unFairFight** [comment]
> I would probably do subscription name rather than the license level. It would take less queries and be more simple.
> 
> You only want the file to be locked to just one subscription? That would be real simple, I was expecting people were going to want to lock files to more than one subscription. Though if it were just one subscription, that'd be easier.

I think it would be cool and also more safe when you would be able to lock a file to one or multiple subcriptions. You could implement a checkbox for every subscription where you can check or uncheck if you can download the file with your subscription.
Would also prefer of having just subscription names instead of naming subscriptions levels.

**Comment by wnelson03** [comment]
This is on my trello to-do list and will come one day
