### ISSUE TITLE
Web HWID login

### ISSUE THREAD

**Issue by untitledentity** [KeyAuth/KeyAuth-Source-Code#57]
The issue is that if I want to log in to an HWID-locked application with a web login; it marks my HWID incorrect.  This is a very simple fix; I can just do this:

if ($json->message ==  hwid_message)
        {
            $_SESSION["user_data"] = (array)$json->info;
            $_SESSION['username'] = $_POST['username'];
            return true;
        }

The issue is that user_data isn't loaded because it only loads if there aren't any errors.

To replicate, login into an HWID-locked application on a server.

To fix you could replace line 158 in includes/api/1.0/login with: 
if ($hwid != NULL && strpos($hwidd, $hwid) === false && $hwidd != NULL)
this way, if the HWID isn't uploaded then you don't check it. You could also check for this in the API function itself, either way, it works.

**Comment by wnelson03** [comment]
Thank you so much for not only identifying the bug, but also providing the fix for it.

I sincerely appreciate it. I accidentally didn't have HWID lock on in my application I use for testing, so I missed this

I've committed your code in c13574b79cc079c4d17528a31220f8ee78705e1a and then also escaped errors in PHP example, since I noticed errors with apostrophes/single quotes aren't shown due to them not being escaped previously.
