### ISSUE TITLE
Suggestion - Manager

### ISSUE THREAD

**Issue by dmnlocco** [KeyAuth/KeyAuth-Source-Code#59]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
Remove or disallow manager to edit refresh OwnerID

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by wnelson03** [comment]
Managers can't own applications so they have no OwnerID. It wouldn't make sense for them to be able for managers to be able to change their owner's OwnerID, that's far too much inherent permission which is the same reason why managers can't change application secret.

However, people have recommended I release an account API which would be able to refresh things such as secret, sellerkey, ownerID. Then you could have a website or a Discord bot that your manager interacts with to refresh your ownerID.

Personally I don't think it's a great idea to give managers that much control of your account, given how your OwnerID is the same for every app and if they refresh it they would fuck up all your other apps. But that's up to you, maybe your manager is your developer.

This account API will probably be released in a couple weeks or a month. It's not top priority so it may not be released in the next update, but some time after it. We'll see.

If you have any other questions, please comment them. Otherwise I'll close this issue tomorrow.
