### ISSUE TITLE
User IDs

### ISSUE THREAD

**Issue by ApoIlos** [KeyAuth/KeyAuth-Source-Code#68]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
Add the user id to the user response on login.

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by wnelson03** [comment]
There's currently no auto-increment ID column for users table.

What do you need this for?

**Comment by ApoIlos** [comment]
> There's currently no auto-increment ID column for users table.
> 
> What do you need this for?

Ah that would make it hard then to impermeant then, i just wanted to able to display the uid in my software thats all but if its gonna be hard to add i can go without :)

**Comment by mazk5145** [comment]
Well Apollos, 

I think it would be possible if you do like after register it would create user id like username lenght = random string + numbers???, then it would store it as user variable.

**Comment by wnelson03** [comment]
Yeah if you want the "cool looking" UID, because if I ever add UIDs they'll be MySQL auto-increment IDs, so like `1` or `29` or `421` for example. UUIDs such as `f04e260c-fe51-4a92-9226-917db3f1bf5e` are bad for performance to use as primary keys in databases I've read, though you're free to do the suggestion mazk said with user variables if you want the UID to "look cool"

**Comment by wnelson03** [comment]
Oops closed. Anyways I'll add the MySQL auto-increment ID to the to-do list to do soon.
