### ISSUE TITLE
Domain blocked in Ukraine

### ISSUE THREAD

**Issue by BUDDGAF** [KeyAuth/KeyAuth-Source-Code#87]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**

**Describe the bug**
I know this is not a bug per se but the Discord is so locked down I have no other way to communicate this to you. The keyauth domain appears to be blocked in Ukraine. Just letting you know in case it is something you wanted to address. 

**Steps To Reproduce**
Visit the domain or attempt to use the service from Ukraine. 

**Expected behavior** 
successful Authentication

**Screenshots**

**Comment by wnelson03** [comment]
I just accessed the website https://keyauth.win fine from a Private Internet Access IP address located in ukraine. Here's that IP address `154.6.130.151`

So, likely, it's just a single Internet Provider in Ukraine blocking KeyAuth, because KeyAuth gets falsely flagged by malware scanners due to there being a lot of obfuscated programs contacting our domain.

I recommend you change your DNS and this will likely solve the issue. Cloudflare's DNS is very easy to setup, you go to https://1.1.1.1 and download it and enable it. Changing your DNS will not slow down your internet speed, and in some cases it will speed up your internet speed because Cloudflare DNS is often faster than the default Internet Providers' DNS servers.

![image](https://user-images.githubusercontent.com/83034852/179623396-0bbc176b-c58c-4684-8359-1d3012aca145.png)

The discord server should be pretty easy to get access to, just respond with these answers for the chat verification.

In the next KeyAuth update, custom domains are coming. And then I will probably setup another domain for just the dashboard where nobody can do API on it (keyauth.win will stay), and then people will always be able to access website, and people can use custom domains if they want to ensure people don't have issues getting blocked.

This update will be here in only a few days :) I think people will like it a lot. There will be no blocking issues then.
